//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practices.SharePoint.Consoles
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CMSMIPEntities : DbContext
    {
        public CMSMIPEntities()
            : base("name=CMSMIPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Org> CMS_BA_IN_DEPT_INFO_V { get; set; }
        public virtual DbSet<User> CMS_SA_USER_INFO_V { get; set; }
    }
}
