//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practices.SharePoint.Consoles
{
    using System;
    using System.Collections.Generic;
    
    public partial class Org
    {
        public long 机构ID { get; set; }
        public string 组织机构编码 { get; set; }
        public string 组织机构名称 { get; set; }
        public Nullable<long> 组织机构上级ID { get; set; }
        public string 组织机构级别 { get; set; }
        public string 组织机构类型 { get; set; }
    }
}
