//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practices.SharePoint.Consoles
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string SP账号 { get; set; }
        public string 用户帐号 { get; set; }
        public string 用户名 { get; set; }
        public string 用户昵称 { get; set; }
        public Nullable<long> 所属部门ID { get; set; }
        public string 所属部门名称 { get; set; }
        public string 所属部门编码 { get; set; }
        public string 用户电子邮件地址 { get; set; }
        public string 用户手机号码 { get; set; }
        public string 用户性别 { get; set; }
        public string 用户身份证号码 { get; set; }
        public string 用户血型 { get; set; }
        public string 用户民族 { get; set; }
        public string 用户文化程度 { get; set; }
        public string 用户在聘职称 { get; set; }
        public string 用户工种 { get; set; }
        public string 用户岗位 { get; set; }
        public string 用户岗次 { get; set; }
        public string 用户人员分类 { get; set; }
        public string 用户政治面貌 { get; set; }
        public string 用户籍贯 { get; set; }
        public string 用户现住址 { get; set; }
        public string 用户原身份 { get; set; }
        public Nullable<System.DateTime> 用户生日 { get; set; }
        public string 用户户籍类别 { get; set; }
        public string 用户婚姻状况 { get; set; }
        public string 人员类别 { get; set; }
        public Nullable<System.DateTime> 参加工作时间 { get; set; }
        public string 办公电话 { get; set; }
        public string 家庭电话 { get; set; }
        public string 用户QQ号 { get; set; }
    }
}
